services:
  nginx:
    image: nginx:1.21-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/front:/var/www/front
      - ./nginx/files:/var/www/files
    ports:
      - 9999:9999
